

## Allowed Values Collection [/allowed_values] 

### List All Allowed Values [GET]

+ Response 200 (application/json)

        {
            "_items": [
            {
                "_updated": "1970-01-01T00:00:00+0000",
                "_created": "1970-01-01T00:00:00+0000",
                "items": [
                    "draft",
                    "ingested",
                    "routed",
                    "fetched",
                    "submitted",
                    "in_progress",
                    "spiked",
                    "published",
                    "killed",
                    "corrected",
                    "scheduled",
                    "recalled"
                ],
                "_links": {
                    "self": {
                        "href": "allowed_values/archive_publish_versions.revert_state",
                        "title": "Allowed_value"
                    }
                },
                "_id": "archive_publish_versions.revert_state",
                "_etag": "38d4a99a1d0170735ed110e2e95dc959f62440ae"
            },
            {
                "_updated": "1970-01-01T00:00:00+0000",
                "_created": "1970-01-01T00:00:00+0000",
                "items": [
                    "text",
                    "preformatted",
                    "audio",
                    "video",
                    "picture",
                    "graphic",
                    "composite",
                    "event"
                ],
                "_links": {
                    "self": {
                        "href": "allowed_values/archive_publish_versions.type",
                        "title": "Allowed_value"
                    }
                },
                "_id": "archive_publish_versions.type",
                "_etag": "534d3615bcc2d3e24b088a84ffe9af4240ca151f"
            },
            {
                "_updated": "1970-01-01T00:00:00+0000",
                "_created": "1970-01-01T00:00:00+0000",
                "items": [
                    "draft",
                    "ingested",
                    "routed",
                    "fetched",
                    "submitted",
                    "in_progress",
                    "spiked",
                    "published",
                    "killed",
                    "corrected",
                    "scheduled",
                    "recalled"
                ],
                "_links": {
                    "self": {
                        "href": "allowed_values/archive_publish_versions.state",
                        "title": "Allowed_value"
                    }
                },
                "_id": "archive_publish_versions.state",
                "_etag": "f94335d13481d34313d77ebd462d39686c6dcaa7"
            },
            {
                "_updated": "1970-01-01T00:00:00+0000",
                "_created": "1970-01-01T00:00:00+0000",
                "items": [
                    "digital",
                    "wire",
                    "all"
                ],
                "_links": {
                    "self": {
                        "href": "allowed_values/subscribers.subscriber_type",
                        "title": "Allowed_value"
                    }
                },
                "_id": "subscribers.subscriber_type",
                "_etag": "3d306dd8b6a4d7dd8a1c16d3eab8819331b663c7"
            },
            {
                "_updated": "1970-01-01T00:00:00+0000",
                "_created": "1970-01-01T00:00:00+0000",
                "items": [
                    "in",
                    "nin",
                    "like",
                    "notlike",
                    "startswith",
                    "endswith",
                    "match",
                    "eq",
                    "ne",
                    "lt",
                    "lte",
                    "gt",
                    "gte"
                ],
                "_links": {
                    "self": {
                        "href": "allowed_values/filter_conditions.operator",
                        "title": "Allowed_value"
                    }
                },
                "_id": "filter_conditions.operator",
                "_etag": "6d8f33f5d60861e278cf80a024d20aca7e071773"
            },
            {
                "_updated": "1970-01-01T00:00:00+0000",
                "_created": "1970-01-01T00:00:00+0000",
                "items": [
                    "anpa_category",
                    "urgency",
                    "keywords",
                    "priority",
                    "slugline",
                    "type",
                    "source",
                    "headline",
                    "ednote",
                    "body_html",
                    "genre",
                    "subject",
                    "desk",
                    "stage",
                    "sms",
                    "place",
                    "ingest_provider",
                    "embargo"
                ],
                "_links": {
                    "self": {
                        "href": "allowed_values/filter_conditions.field",
                        "title": "Allowed_value"
                    }
                },
                "_id": "filter_conditions.field",
                "_etag": "3d38112e0cb5a0c467b24aad978c269e443bcf27"
            }
            ]
        }
