## Backend Meta Collection [/backend_meta] 

### List All Backend Meta [GET]

+ Response 200 (application/json)

        {
            "_items": [],
            "modules": [
                {
                    "href": "https://github.com/superdesk/superdesk-core/tree/master",
                    "name": "superdesk-core",
                    "version": "master"
                },
                {
                    "href": "https://github.com/superdesk/superdesk-client-core/tree/master",
                    "name": "superdesk-client-core",
                    "version": "master"
                },
                {
                    "href": "https://github.com/superdesk/superdesk-analytics/tree/master",
                    "name": "superdesk-analytics",
                    "version": "master"
                },
                {
                    "href": "https://github.com/superdesk/superdesk-publisher/tree/master",
                    "name": "superdesk-publisher",
                    "version": "master"
                }
            ],
            "meta_rev": "fc745fea5320482ee06d410acd387602c240caaa\n"
        }

