## Routing Schemes Collection [/routing_schemes] 

### List All Routing Schemes [GET]

+ Response 200 (application/json)

        {
            "_items": [
                {
                    "_id": "5acb97facdfe3800e58798f5",
                    "rules": [
                        {
                            "schedule": {
                                "day_of_week": [
                                    "WED",
                                    "THU",
                                    "FRI",
                                    "SAT",
                                    "SUN",
                                    "TUE",
                                    "MON"
                                ],
                                "time_zone": "UTC",
                                "hour_of_day_to": "23:59:00",
                                "hour_of_day_from": "00:00:00"
                            },
                            "actions": {
                                "publish": [],
                                "fetch": [
                                    {
                                        "macro": "assign_status",
                                        "desk": "5ab27ab6cdfe38023cd29eac",
                                        "stage": "5acb982bcdfe3800e58798f7"
                                    }
                                ],
                                "exit": false
                            },
                            "filter": null,
                            "name": "IPTC routed"
                        }
                    ],
                    "name": "IPTC routed"
                }
            ]
        }

### Create A New Routing Scheme [POST]

Creates a new routing scheme. Creation of a routing scheme will fail if:

 - There is no rule defined in routing scheme
 - If there are multiple rules with the same name
 - If an unknown field provide in the rule definition
 - If there's no name defined
 - If there's no action defined in routing scheme
 - If an empty schedule is given
 - If a schedule is given and if the date and time formats are not recognized

+ Request (application/json)

    + Body
        
            {
                "name": "Test"
            }

    + Schema

            {
                "name": {
                    "type": "string",
                    "iunique": true,
                    "required": true,
                    "nullable": false,
                    "empty": false
                },
                "rules": {
                    "type": "list",
                    "schema": {
                        "type": "dict",
                        "schema": {
                            "name": {
                                "type": "string"
                            },
                            "filter": "{content_filter_id}",
                            "actions": {
                                "type": "dict",
                                "schema": {
                                    "fetch": {
                                        "type": "list",
                                        "schema": {
                                            "type": "dict",
                                            "schema": {
                                                "desk": "{desk_id}",
                                                "stage": "{stage_id}",
                                                "macro": {"type": "string"}
                                            }
                                        }
                                    },
                                    "publish": {
                                        "type": "list",
                                        "schema": {
                                            "type": "dict",
                                            "schema": {
                                                "desk": "{desk_id}",
                                                "stage": "{stage_id}",
                                                "macro": {"type": "string"},
                                                "target_subscribers": {
                                                    "type": "list",
                                                    "nullable": true
                                                },
                                                "target_types": {
                                                    "type": "list",
                                                    "nullable": true
                                                }
                                            }
                                        }
                                    },
                                    "exit": {
                                        "type": "boolean"
                                    },
                                    "preserve_desk": {
                                        "type": "boolean"
                                    }
                                }
                            },
                            "schedule": {
                                "type": "dict",
                                "nullable": true,
                                "schema": {
                                    "day_of_week": {
                                        "type": "list"
                                    },
                                    "hour_of_day_from": {
                                        "type": "string",
                                        "nullable": true
                                    },
                                    "hour_of_day_to": {
                                        "type": "string",
                                        "nullable": true
                                    },
                                    "time_zone": {
                                        "type": "string",
                                        "nullable": false,
                                        "default": "UTC"
                                    }
                                }
                            }
                        }
                    }
                }
            }

+ Response 201 (application/json)

+ Response 400 (application/json)

+ Response 412 (application/json)        

## A Routing Scheme [/routing_schemes/{routing_scheme_id}]

+ Parameters

    - routing_scheme_id (string) ... routing scheme id

### Details of A Routing Scheme [GET]

+ Response 200 (application/json)

    + Body

            {
                "_id": "5bc08c26bfb76600e3158e98",
                "_links": {
                    "self": {
                        "title": "Routing_scheme",
                        "href": "routing_schemes/5bc08c26bfb76600e3158e98"
                    },
                    "parent": {
                        "title": "home",
                        "href": "/"
                    },
                    "collection": {
                        "title": "routing_schemes",
                        "href": "routing_schemes"
                    }
                },
                "_etag": "c0caa7f13e2eb2eaf15a659e425d1fd5ba09c918",
                "_updated": "2018-10-12T11:57:26+0000",
                "_type": "routing_schemes",
                "name": "To Karel's desk",
                "_created": "2018-10-12T11:57:26+0000",
                "rules": [
                    {
                        "actions": {
                            "publish": [],
                            "fetch": [
                                {
                                    "desk": "5bc0893ebfb76600e3158e6e",
                                    "stage": "5bc0893ebfb76600e3158e6d"
                                }
                            ],
                            "exit": true
                        },
                        "schedule": {
                            "time_zone": "UTC",
                            "hour_of_day_from": null,
                            "hour_of_day_to": null,
                            "day_of_week": [
                                "MON",
                                "TUE",
                                "WED",
                                "THU",
                                "FRI",
                                "SAT",
                                "SUN"
                            ]
                        },
                        "filter": null,
                        "name": "Fetch to Karel's deks"
                    }
                ]
            }
           

### Update A Routing Scheme [PATCH]

Updates the routing scheme. Update of the routing scheme will fail if:

 - If all rules are removed
 - If there are multiple rules with the same name
 - If an unknown field provide in the rule definition
 - If name is removed
 - If the actions areremoved
 - If an empty schedule is given
 - If a schedule is given and if the date and time formats are not recognized

+ Request (application/json)

    + Headers
    
            If-Match: {_etag}
    
    + Body

            { 
                "name": "New name"
            }

+ Response 200 (application/json)

+ Response 403 (application/json)

## Delete A Routing Scheme [DELETE]      

Deletes the routing scheme by given id. A routing scheme will fail to delete if:

 - It is in use by a ingest channel

+ Request (application/json)

        {}

+ Response 204 (application/json)

+ Response 412 (application/json)