## Media References Collection [/media_references] 

### List All Media References [GET]

+ Response 200 (application/json)

        {
            "_items": [
                {
                    "_id": "5ab39303cdfe3800e091fab8",
                    "associated_id": "urn:newsml:sdp-master.test.superdesk.org:2018-03-22T11:26:36.102596:52b5e92f-6f9d-4260-9acf-e72efd5cd494",
                    "_etag": "85fa3fec3d3d13311e3876b4aa972af30d0e53f6",
                    "_updated": "2018-03-22T11:26:59+0000",
                    "item_id": "urn:newsml:sdp-master.test.superdesk.org:2018-03-22T11:23:00.895488:3c3b1221-311f-4c72-bf95-921a138cd49a",
                    "_created": "2018-03-22T11:26:59+0000",
                    "_links": {
                        "self": {
                            "title": "Media_reference",
                            "href": "media_references/5ab39303cdfe3800e091fab8"
                        }
                    },
                    "published": false,
                    "media_id": "5ab392eccdfe3800e091fa9a"
                },
                {
                    "_id": "5ab39303cdfe3800e091fab9",
                    "associated_id": "urn:newsml:sdp-master.test.superdesk.org:2018-03-22T11:26:36.102596:52b5e92f-6f9d-4260-9acf-e72efd5cd494",
                    "_etag": "61c43b10767a2e5b68b5c35703e58996363c27d7",
                    "_updated": "2018-03-22T11:26:59+0000",
                    "item_id": "urn:newsml:sdp-master.test.superdesk.org:2018-03-22T11:23:00.895488:3c3b1221-311f-4c72-bf95-921a138cd49a",
                    "_created": "2018-03-22T11:26:59+0000",
                    "_links": {
                        "self": {
                            "title": "Media_reference",
                            "href": "media_references/5ab39303cdfe3800e091fab9"
                        }
                    },
                    "published": false,
                    "media_id": "5ab392eccdfe3800e091faa5"
                }
            ]
        }



## A Media Reference [/vocabularies/{media_reference_id}]

+ Parameters

    - media_reference_id (string) ... media_refence id

### Details of A Media Reference [GET]

+ Response 200 (application/json)

    + Body

            {
                
            }
           

