

## Spikes Collection [/spikes] 

### List All Spikes [GET]

+ Response 200 (application/json)

        {
            "_items": [
            {
                "_id": "urn:newsml:sdp-master.test.superdesk.org:2018-05-01T15:48:10.657187:87a85ca8-0878-4d54-985f-0698e99d0298",
                "firstcreated": "2018-05-01T15:48:10+0000",
                "task": {
                    "desk": "5ab27ab6cdfe38023cd29eac",
                    "user": "5ab27997cdfe38023cd29e97",
                    "stage": "5ab27ab6cdfe38023cd29eaa"
                },
                "operation": "spike",
                "pubstatus": "usable",
                "version_creator": "5ab27997cdfe38023cd29e97",
                "unique_name": "#104",
                "flags": {
                    "marked_for_sms": false,
                    "marked_for_not_publication": false,
                    "marked_archived_only": false,
                    "marked_for_legal": false
                },
                "_created": "2018-05-01T15:48:10+0000",
                "sign_off": "NA",
                "slugline": "Karakazin",
                "template": "5ab27ad6cdfe38023cd29eb3",
                "unique_id": 104,
                "versioncreated": "2018-05-01T15:48:17+0000",
                "assignment_id": null,
                "family_id": "urn:newsml:sdp-master.test.superdesk.org:2018-05-01T15:48:10.657187:87a85ca8-0878-4d54-985f-0698e99d0298",
                "_etag": "bf5ba75964dbd9aad7de2a51ce0e0d88ff8ed0a5",
                "_links": {
                    "self": {
                        "title": "Spike",
                        "href": "spikes/urn:newsml:sdp-master.test.superdesk.org:2018-05-01T15:48:10.657187:87a85ca8-0878-4d54-985f-0698e99d0298"
                    }
                },
                "schedule_settings": {
                    "time_zone": null,
                    "utc_embargo": null
                },
                "_current_version": 3,
                "profile": "5ab27ad6cdfe38023cd29eb1",
                "lock_time": null,
                "genre": [
                    {
                        "name": "Article (news)",
                        "qcode": "Article"
                    }
                ],
                "_type": "archive",
                "format": "HTML",
                "lock_action": null,
                "expiry": null,
                "original_creator": "5ab27997cdfe38023cd29e97",
                "revert_state": "in_progress",
                "source": "NaregsYarde",
                "lock_user": null,
                "language": "en",
                "guid": "urn:newsml:sdp-master.test.superdesk.org:2018-05-01T15:48:10.657187:87a85ca8-0878-4d54-985f-0698e99d0298",
                "event_id": "tag:sdp-master.test.superdesk.org:2018:feb584e0-9dc1-4b38-a6c9-117c337fc906",
                "force_unlock": true,
                "place": [],
                "_updated": "2018-05-01T15:48:44+0000",
                "urgency": 3,
                "priority": 6,
                "state": "spiked",
                "lock_session": null,
                "version": 2,
                "type": "text"
            }]
        }


