## A Suggestion [/suggestions/{item_id}]

+ Parameters

    - item_id (string) ... item id

### Details of A Suggestion [GET]

Returns a list of items related to the given item. The given item id is retrieved
from the lookup dictionary as 'item_id'

+ Response 200 (application/json)

    + Body

            {
                
            }
           
