

## Planning Export Templates Collection [/planning_export_templates] 

### List All Planning Templates [GET]

+ Response 200 (application/json)

        {
            "_items": [{
                "name": "conf_template",
                "label": "Default Planning Template",
                "type": "planning",
                "data": {
                    "body_html_template": "test_planning_export_template.html"
                }
            }]
        }
