## Planning Collection [/planning] 

### List All Planning Items [GET]

+ Response 200 (application/json)

        {
            "_items": [
                {
                    "_id": "urn:newsml:sdp-master.test.superdesk.org:2018-03-21T15:33:18.981160:02f87be4-9045-4b91-af2d-25fa5190dd31",
                    "lock_action": null,
                    "subject": [
                        {
                            "qcode": "01001000",
                            "name": "archaeology",
                            "parent": "01000000"
                        }
                    ],
                    "state": "draft",
                    "_links": {
                        "self": {
                            "href": "planning/urn:newsml:sdp-master.test.superdesk.org:2018-03-21T15:33:18.981160:02f87be4-9045-4b91-af2d-25fa5190dd31",
                            "title": "Planning"
                        }
                    },
                    "_etag": "a4bb1bfc75a7271a06de446fc892e0cb0a70d3c8",
                    "_type": "planning",
                    "guid": "urn:newsml:sdp-master.test.superdesk.org:2018-03-21T15:33:18.981160:02f87be4-9045-4b91-af2d-25fa5190dd31",
                    "urgency": 2,
                    "lock_user": null,
                    "original_creator": "5ab27997cdfe38023cd29e97",
                    "_created": "2018-03-21T15:33:18+0000",
                    "type": "planning",
                    "lock_time": null,
                    "coverages": [
                        {
                            "assigned_to": {
                                "user": "5ab27997cdfe38023cd29e97",
                                "assigned_date_desk": "2018-03-21T15:34:53+0000",
                                "coverage_provider": null,
                                "state": "draft",
                                "desk": "5ab27ab6cdfe38023cd29eac",
                                "assignment_id": "5ab27b9dcdfe38023cd29ed8",
                                "assignor_desk": "5ab27997cdfe38023cd29e97",
                                "assigned_date_user": "2018-03-21T15:34:53+0000",
                                "priority": 2,
                                "assignor_user": "5ab27997cdfe38023cd29e97"
                            },
                            "news_coverage_status": {
                                "qcode": "ncostat:int",
                                "name": "coverage intended",
                                "label": "Planned"
                            },
                            "firstcreated": "2018-03-21T15:34:53+0000",
                            "workflow_status": "draft",
                            "original_creator": "5ab27997cdfe38023cd29e97",
                            "coverage_id": "urn:newsml:sdp-master.test.superdesk.org:2018-03-21T15:34:53.138479:970e15c5-ed8c-4311-abb4-c59ef873dcb9",
                            "planning": {
                                "scheduled": "2018-03-21T15:33:02+0000",
                                "slugline": "plnon12",
                                "genre": [
                                    {
                                        "qcode": "Article",
                                        "name": "Article (news)"
                                    }
                                ],
                                "g2_content_type": "text"
                            }
                        }
                    ],
                    "agendas": [
                        "5ab27a0dcdfe38023cd29e9d"
                    ],
                    "slugline": "plnon12",
                    "_updated": "2018-03-21T15:34:55+0000",
                    "anpa_category": [
                        {
                            "subject": "",
                            "qcode": "f1",
                            "name": "FIXME1",
                            "translations": {
                                "name": {
                                    "fr": "FIXME1-fr",
                                    "es": "FIXME1-es"
                                }
                            }
                        },
                        {
                            "subject": "",
                            "qcode": "f2",
                            "name": "FIXME2",
                            "translations": {
                                "name": {
                                    "fr": "FIXME2-fr",
                                    "es": "FIXME2-es"
                                }
                            }
                        }
                    ],
                    "flags": {
                        "marked_for_not_publication": true
                    },
                    "planning_date": "2018-03-21T15:33:02+0000",
                    "lock_session": null,
                    "item_class": "plinat:newscoverage",
                    "version_creator": "5ab27997cdfe38023cd29e97"
                }
            ]
        }


### Create A New Planning Item [POST]

Creates a new planning item. During the creation system will check if there'a a **planning_type** record.
If **headline** is enabled in planning_type then it will use the name of the event in the **headline** field.

+ Request (application/json)

    + Body
        
            {
                "item_class": "item class value",
                "headline": "test headline",
                "agendas": ["5ab27a0dcdfe38023cd29e9d"]
            }

    + Schema

            {
                "internal_note": {
                    "type": "string",
                    "nullable": true
                },
                "place": {
                    "type": "list",
                    "mapping": {
                        "type": "object",
                        "dynamic": false,
                        "properties": {
                            "qcode": {
                                "type": "string",
                                "index": "not_analyzed"
                            },
                            "country": {
                                "type": "string",
                                "index": "not_analyzed"
                            },
                            "rel": {
                                "type": "string",
                                "index": "not_analyzed"
                            },
                            "location": {
                                "type": "geo_point"
                            },
                            "locality": {
                                "type": "string",
                                "index": "not_analyzed"
                            },
                            "feature_class": {
                                "type": "string",
                                "index": "not_analyzed"
                            },
                            "world_region_code": {
                                "type": "string",
                                "index": "not_analyzed"
                            },
                            "state_code": {
                                "type": "string",
                                "index": "not_analyzed"
                            },
                            "name": {
                                "type": "string",
                                "index": "not_analyzed"
                            },
                            "code": {
                                "type": "string",
                                "index": "not_analyzed"
                            },
                            "state": {
                                "type": "string",
                                "index": "not_analyzed"
                            },
                            "world_region": {
                                "type": "string",
                                "index": "not_analyzed"
                            },
                            "country_code": {
                                "type": "string",
                                "index": "not_analyzed"
                            },
                            "scheme": {
                                "type": "string",
                                "index": "not_analyzed"
                            },
                            "locality_code": {
                                "type": "string",
                                "index": "not_analyzed"
                            }
                        }
                    },
                    "nullable": true
                },
                "agendas": {
                    "type": "list",
                    "mapping": {
                        "type": "string",
                        "index": "not_analyzed"
                    },
                    "schema": {
                        "type": "objectid",
                        "data_relation": {
                            "resource": "agenda",
                            "embeddable": true,
                            "field": "_id"
                        },
                        "required": false,
                        "nullable": false
                    }
                },
                "ednote": {
                    "type": "string",
                    "nullable": true
                },
                "version_creator": {
                    "type": "objectid",
                    "data_relation": {
                        "resource": "users",
                        "embeddable": true,
                        "field": "_id"
                    },
                    "required": false,
                    "nullable": false
                },
                "event_item": {
                    "type": "string",
                    "data_relation": {
                        "resource": "events",
                        "embeddable": true,
                        "field": "_id"
                    },
                    "required": false,
                    "mapping": {
                        "type": "string",
                        "index": "not_analyzed"
                    },
                    "nullable": false
                },
                "lock_session": {
                    "type": "objectid",
                    "data_relation": {
                        "resource": "auth",
                        "embeddable": true,
                        "field": "_id"
                    },
                    "required": false,
                    "versioned": false,
                    "nullable": false
                },
                "lock_action": {
                    "type": "string",
                    "mapping": {
                        "type": "string",
                        "index": "not_analyzed"
                    },
                    "nullable": true
                },
                "original_creator": {
                    "type": "objectid",
                    "data_relation": {
                        "resource": "users",
                        "embeddable": true,
                        "field": "_id"
                    },
                    "required": false,
                    "nullable": false
                },
                "name": {
                    "type": "string"
                },
                "subject": {
                    "type": "list",
                    "mapping": {
                        "type": "object",
                        "properties": {
                            "qcode": {
                                "type": "string",
                                "index": "not_analyzed"
                            },
                            "name": {
                                "type": "string",
                                "index": "not_analyzed"
                            }
                        }
                    }
                },
                "profile": {
                    "type": "string",
                    "nullable": true
                },
                "_planning_schedule": {
                    "type": "list",
                    "mapping": {
                        "type": "nested",
                        "properties": {
                            "scheduled": {
                                "type": "date"
                            },
                            "coverage_id": {
                                "type": "string",
                                "index": "not_analyzed"
                            }
                        }
                    }
                },
                "priority": {
                    "type": "integer",
                    "nullable": true
                },
                "lock_time": {
                    "type": "datetime",
                    "versioned": false
                },
                "coverages": {
                    "type": "list",
                    "mapping": {
                        "type": "nested",
                        "properties": {
                            "planning": {
                                "type": "object",
                                "properties": {
                                    "slugline": {
                                        "type": "string",
                                        "fields": {
                                            "phrase": {
                                                "type": "string",
                                                "search_analyzer": "phrase_prefix_analyzer",
                                                "analyzer": "phrase_prefix_analyzer"
                                            }
                                        }
                                    }
                                }
                            },
                            "coverage_id": {
                                "type": "string",
                                "index": "not_analyzed"
                            },
                            "assigned_to": {
                                "type": "object",
                                "properties": {
                                    "state": {
                                        "type": "string",
                                        "index": "not_analyzed"
                                    },
                                    "assignment_id": {
                                        "type": "string",
                                        "index": "not_analyzed"
                                    }
                                }
                            }
                        }
                    },
                    "schema": {
                        "type": "dict",
                        "schema": {
                            "guid": {
                                "type": "string",
                                "unique": true,
                                "mapping": {
                                    "type": "string",
                                    "index": "not_analyzed"
                                }
                            },
                            "planning": {
                                "type": "dict",
                                "schema": {
                                    "slugline": {
                                        "type": "string",
                                        "mapping": {
                                            "type": "string",
                                            "fields": {
                                                "phrase": {
                                                    "type": "string",
                                                    "search_analyzer": "phrase_prefix_analyzer",
                                                    "analyzer": "phrase_prefix_analyzer"
                                                }
                                            }
                                        }
                                    },
                                    "planning_ext_property": {
                                        "type": "list",
                                        "mapping": {
                                            "properties": {
                                                "qcode": {
                                                    "type": "string",
                                                    "index": "not_analyzed"
                                                },
                                                "value": {
                                                    "type": "string",
                                                    "index": "not_analyzed"
                                                },
                                                "name": {
                                                    "type": "string",
                                                    "index": "not_analyzed"
                                                }
                                            }
                                        }
                                    },
                                    "genre": {
                                        "type": "list",
                                        "mapping": {
                                            "type": "object",
                                            "properties": {
                                                "name": {
                                                    "type": "string",
                                                    "index": "not_analyzed"
                                                },
                                                "qcode": {
                                                    "type": "string",
                                                    "index": "not_analyzed"
                                                }
                                            }
                                        },
                                        "nullable": true
                                    },
                                    "scheduled": {
                                        "type": "datetime"
                                    },
                                    "item_count": {
                                        "type": "string",
                                        "mapping": {
                                            "type": "string",
                                            "index": "not_analyzed"
                                        }
                                    },
                                    "ednote": {
                                        "type": "string",
                                        "nullable": true
                                    },
                                    "item_class": {
                                        "type": "string",
                                        "mapping": {
                                            "type": "string",
                                            "index": "not_analyzed"
                                        }
                                    },
                                    "g2_content_type": {
                                        "type": "string",
                                        "mapping": {
                                            "type": "string",
                                            "index": "not_analyzed"
                                        }
                                    },
                                    "credit_line": {
                                        "type": "list",
                                        "mapping": {
                                            "type": "string"
                                        }
                                    },
                                    "keyword": {
                                        "type": "list",
                                        "mapping": {
                                            "type": "string"
                                        }
                                    },
                                    "news_content_characteristics": {
                                        "type": "list",
                                        "mapping": {
                                            "properties": {
                                                "name": {
                                                    "type": "string",
                                                    "index": "not_analyzed"
                                                },
                                                "value": {
                                                    "type": "string",
                                                    "index": "not_analyzed"
                                                }
                                            }
                                        }
                                    },
                                    "internal_note": {
                                        "type": "string"
                                    },
                                    "subject": {
                                        "type": "list",
                                        "mapping": {
                                            "type": "object",
                                            "properties": {
                                                "qcode": {
                                                    "type": "string",
                                                    "index": "not_analyzed"
                                                },
                                                "name": {
                                                    "type": "string",
                                                    "index": "not_analyzed"
                                                }
                                            }
                                        }
                                    },
                                    "description_text": {
                                        "type": "string",
                                        "nullable": true
                                    },
                                    "service": {
                                        "type": "list",
                                        "mapping": {
                                            "properties": {
                                                "qcode": {
                                                    "type": "string",
                                                    "index": "not_analyzed"
                                                },
                                                "name": {
                                                    "type": "string",
                                                    "index": "not_analyzed"
                                                }
                                            }
                                        }
                                    },
                                    "headline": {
                                        "type": "string"
                                    },
                                    "coverage_provider": {
                                        "type": "string",
                                        "mapping": {
                                            "type": "string",
                                            "index": "not_analyzed"
                                        }
                                    },
                                    "dateline": {
                                        "type": "list",
                                        "mapping": {
                                            "type": "string"
                                        }
                                    },
                                    "language": {
                                        "type": "list",
                                        "mapping": {
                                            "type": "string"
                                        }
                                    },
                                    "by": {
                                        "type": "list",
                                        "mapping": {
                                            "type": "string"
                                        }
                                    }
                                }
                            },
                            "coverage_id": {
                                "type": "string",
                                "mapping": {
                                    "type": "string",
                                    "index": "not_analyzed"
                                }
                            },
                            "previous_status": {
                                "type": "string"
                            },
                            "assigned_to": {
                                "type": "dict",
                                "mapping": {
                                    "type": "object",
                                    "properties": {
                                        "state": {
                                            "type": "string",
                                            "index": "not_analyzed"
                                        },
                                        "assignment_id": {
                                            "type": "string",
                                            "index": "not_analyzed"
                                        }
                                    }
                                }
                            },
                            "version_creator": {
                                "type": "objectid",
                                "data_relation": {
                                    "resource": "users",
                                    "embeddable": true,
                                    "field": "_id"
                                },
                                "required": false,
                                "nullable": false
                            },
                            "workflow_status": {
                                "type": "string"
                            },
                            "firstcreated": {
                                "type": "datetime"
                            },
                            "versioncreated": {
                                "type": "datetime"
                            },
                            "news_coverage_status": {
                                "type": "dict",
                                "schema": {
                                    "qcode": {
                                        "type": "string"
                                    },
                                    "name": {
                                        "type": "string"
                                    },
                                    "label": {
                                        "type": "string"
                                    }
                                }
                            },
                            "original_creator": {
                                "type": "objectid",
                                "data_relation": {
                                    "resource": "users",
                                    "embeddable": true,
                                    "field": "_id"
                                },
                                "required": false,
                                "nullable": false
                            }
                        }
                    },
                    "default": []
                },
                "word_count": {
                    "type": "integer"
                },
                "keywords": {
                    "type": "list",
                    "mapping": {
                        "type": "string"
                    }
                },
                "revert_state": {
                    "type": "string",
                    "allowed": [
                        "draft",
                        "ingested",
                        "routed",
                        "fetched",
                        "submitted",
                        "in_progress",
                        "spiked",
                        "published",
                        "killed",
                        "corrected",
                        "scheduled",
                        "recalled"
                    ],
                    "mapping": {
                        "type": "string",
                        "index": "not_analyzed"
                    }
                },
                "firstcreated": {
                    "type": "datetime"
                },
                "versioncreated": {
                    "type": "datetime"
                },
                "urgency": {
                    "type": "integer",
                    "nullable": true
                },
                "company_codes": {
                    "type": "list",
                    "mapping": {
                        "type": "object",
                        "properties": {
                            "qcode": {
                                "type": "string",
                                "index": "not_analyzed"
                            },
                            "name": {
                                "type": "string",
                                "index": "not_analyzed"
                            },
                            "security_exchange": {
                                "type": "string",
                                "index": "not_analyzed"
                            }
                        }
                    }
                },
                "slugline": {
                    "type": "string",
                    "mapping": {
                        "type": "string",
                        "fields": {
                            "phrase": {
                                "type": "string",
                                "search_analyzer": "phrase_prefix_analyzer",
                                "analyzer": "phrase_prefix_analyzer"
                            }
                        }
                    }
                },
                "pubstatus": {
                    "type": "string",
                    "allowed": [
                        "usable",
                        "cancelled"
                    ],
                    "mapping": {
                        "type": "string",
                        "index": "not_analyzed"
                    },
                    "nullable": true
                },
                "genre": {
                    "type": "list",
                    "mapping": {
                        "type": "object",
                        "properties": {
                            "name": {
                                "type": "string",
                                "index": "not_analyzed"
                            },
                            "qcode": {
                                "type": "string",
                                "index": "not_analyzed"
                            }
                        }
                    },
                    "nullable": true
                },
                "expired": {
                    "type": "boolean",
                    "default": false
                },
                "abstract": {
                    "type": "string",
                    "nullable": true
                },
                "item_class": {
                    "type": "string",
                    "default": "plinat:newscoverage"
                },
                "language": {
                    "type": "string",
                    "mapping": {
                        "type": "string",
                        "index": "not_analyzed"
                    },
                    "nullable": true
                },
                "unique_id": {
                    "type": "string",
                    "mapping": {
                        "type": "string",
                        "index": "not_analyzed"
                    }
                },
                "recurrence_id": {
                    "type": "string",
                    "mapping": {
                        "type": "string",
                        "index": "not_analyzed"
                    },
                    "nullable": true
                },
                "planning_date": {
                    "type": "datetime",
                    "nullable": false
                },
                "type": {
                    "type": "string",
                    "mapping": {
                        "type": "string",
                        "index": "not_analyzed"
                    },
                    "default": "planning"
                },
                "lock_user": {
                    "type": "objectid",
                    "data_relation": {
                        "resource": "users",
                        "embeddable": true,
                        "field": "_id"
                    },
                    "required": false,
                    "versioned": false,
                    "nullable": false
                },
                "expiry": {
                    "type": "datetime",
                    "nullable": true
                },
                "guid": {
                    "type": "string",
                    "unique": true,
                    "mapping": {
                        "type": "string",
                        "index": "not_analyzed"
                    }
                },
                "state": {
                    "type": "string",
                    "allowed": [
                        "draft",
                        "active",
                        "ingested",
                        "scheduled",
                        "killed",
                        "cancelled",
                        "rescheduled",
                        "postponed",
                        "spiked"
                    ],
                    "mapping": {
                        "type": "string",
                        "index": "not_analyzed"
                    },
                    "default": "draft"
                },
                "description_text": {
                    "type": "string",
                    "nullable": true
                },
                "flags": {
                    "type": "dict",
                    "schema": {
                        "marked_for_not_publication": {
                            "type": "boolean",
                            "default": false
                        }
                    }
                },
                "_id": {
                    "type": "string",
                    "unique": true
                },
                "headline": {
                    "type": "string"
                },
                "anpa_category": {
                    "type": "list",
                    "mapping": {
                        "type": "object",
                        "properties": {
                            "qcode": {
                                "type": "string",
                                "index": "not_analyzed"
                            },
                            "name": {
                                "type": "string",
                                "index": "not_analyzed"
                            }
                        }
                    },
                    "nullable": true
                }
            }

+ Response 201 (application/json)

+ Response 400 (application/json)

+ Response 412 (application/json)


## A Planning Item [/planning/{planning_id}]

+ Parameters

    - planning_id (string) ... planning id

### Details of A Planning Item [GET]

+ Response 200 (application/json)

    + Body

            {
                "_id": "urn:newsml:sdp-master.test.superdesk.org:2018-03-21T15:33:18.981160:02f87be4-9045-4b91-af2d-25fa5190dd31",
                "lock_action": null,
                "urgency": 2,
                "subject": [
                    {
                        "qcode": "01001000",
                        "name": "archaeology",
                        "parent": "01000000"
                    }
                ],
                "state": "draft",
                "_etag": "a4bb1bfc75a7271a06de446fc892e0cb0a70d3c8",
                "_type": "planning",
                "guid": "urn:newsml:sdp-master.test.superdesk.org:2018-03-21T15:33:18.981160:02f87be4-9045-4b91-af2d-25fa5190dd31",
                "version_creator": "5ab27997cdfe38023cd29e97",
                "lock_user": null,
                "original_creator": "5ab27997cdfe38023cd29e97",
                "_created": "2018-03-21T15:33:18+0000",
                "type": "planning",
                "lock_time": null,
                "agendas": [
                    "5ab27a0dcdfe38023cd29e9d"
                ],
                "slugline": "plnon12",
                "_updated": "2018-03-21T15:34:55+0000",
                "anpa_category": [
                    {
                        "subject": "",
                        "qcode": "f1",
                        "name": "FIXME1",
                        "translations": {
                            "name": {
                                "fr": "FIXME1-fr",
                                "es": "FIXME1-es"
                            }
                        }
                    },
                    {
                        "subject": "",
                        "qcode": "f2",
                        "name": "FIXME2",
                        "translations": {
                            "name": {
                                "fr": "FIXME2-fr",
                                "es": "FIXME2-es"
                            }
                        }
                    }
                ],
                "flags": {
                    "marked_for_not_publication": true
                },
                "planning_date": "2018-03-21T15:33:02+0000",
                "lock_session": null,
                "item_class": "plinat:newscoverage",
                "coverages": [
                    {
                        "assigned_to": {
                            "user": "5ab27997cdfe38023cd29e97",
                            "assigned_date_desk": "2018-03-21T15:34:53+0000",
                            "coverage_provider": null,
                            "state": "draft",
                            "desk": "5ab27ab6cdfe38023cd29eac",
                            "assignment_id": "5ab27b9dcdfe38023cd29ed8",
                            "assignor_desk": "5ab27997cdfe38023cd29e97",
                            "assigned_date_user": "2018-03-21T15:34:53+0000",
                            "priority": 2,
                            "assignor_user": "5ab27997cdfe38023cd29e97"
                        },
                        "news_coverage_status": {
                            "qcode": "ncostat:int",
                            "name": "coverage intended",
                            "label": "Planned"
                        },
                        "firstcreated": "2018-03-21T15:34:53+0000",
                        "workflow_status": "draft",
                        "planning": {
                            "scheduled": "2018-03-21T15:33:02+0000",
                            "slugline": "plnon12",
                            "genre": [
                                {
                                    "qcode": "Article",
                                    "name": "Article (news)"
                                }
                            ],
                            "g2_content_type": "text"
                        },
                        "coverage_id": "urn:newsml:sdp-master.test.superdesk.org:2018-03-21T15:34:53.138479:970e15c5-ed8c-4311-abb4-c59ef873dcb9",
                        "original_creator": "5ab27997cdfe38023cd29e97"
                    }
                ]
            }
           

### Update A Planning Item [PATCH]

- Canceling a coverage will cancel the assignment item.
- Updating **internal_notes** field will raise an interna event 
- Updating scheduled times for coverages will raise an internal event
- Updates to planning items will be recorded in planning history entity

Planning item update will fail if:
- A coverage is removed but there's an assignment for the coverage
- Planning item does not exist
- An assignment is removed but there's a non draft state coverage for the assignment
- A coverage is updated but the related assignment does not exist

+ Request (application/json)

    + Headers
    
            If-Match: {_etag}
    
    + Body

            {
                "coverages": [
                    {
                        "workflow_status": "draft",
                        "news_coverage_status": {
                        "qcode": "ncostat:int"
                        },
                        "planning": {
                            "ednote": "test coverage",
                            "headline": "test headline",
                            "slugline": "test slugline"
                        }
                    }
                ]
            }

+ Response 200 (application/json)

+ Response 403 (application/json)


## Planning Item Duplicate Resource [/planning/{planning_id}/duplicate] 

Duplicates the given planning item. Duplicating a Planning item will link to the same Planning Item. But if the 
planning item is expired, the link to event will be removed.

If the duplicated planning item has been published, duplicate won't get auto published. Coverages in the duplicate
will revert to **draft** state. 


+ Parameters

    - planning_id (string) ... planning item id

### Duplicate A Planning Item [POST]

+ Response 200 (application/json)

    + Body

            {
                
            }

    + Schema

            {

            }           


## Planning Item Lock Resource [/planning/{planning_id}/lock] 

Locks the planning item for a given user. This will prevent other users editing or moving the item.
Lock will fail if:
- the planning item is locked to another user
- the planning item is recurring and another instance of recurrances is locked to another user


+ Parameters

    - planning_id (string) ... planning item id

### Lock An Planning Item [POST]

+ Response 200 (application/json)

    + Body

            {
                "lock_action": "edit"
            }

    + Schema

            {"lock_action": {"type": "string"}}                   



## Planning Item Unlock Resource [/planning/{planning_id}/unlock] 

Unlocks the planning item for a given user. This will let other users editing or moving the item.
Unlock will fail if:
- Lock is not created by the same user
- planning item does not exist
- there's no lock on item


+ Parameters

    - planning_id (string) ... planning item id

### Unlock An Planning Item [POST]

+ Response 200 (application/json)

    + Body

            {
                
            }

    + Schema

            {

            }                


## Spike [/planning/spike/{planning_id}]

Spikes a planning item.

+ Parameters

    - planning_id (string) ... planning id

### Spike A Planning Item [PATCH]


+ Request (application/json)

    + Headers
    
            If-Match: {_etag}
    
    + Body

            { 
                "state": "spiked",
                "update_method": "all"
            }

+ Response 200 (application/json)

+ Response 403 (application/json)


## Unspike [/planning/unspike/{planning_id}]

Unspikes a planning item. The state of the unspiked item will revert to **draft**

+ Parameters

    - planning_id (string) ... planning item id

### Unspike A Planning Item [PATCH]

+ Request (application/json)

    + Headers
    
            If-Match: {_etag}
    
    + Body

            { 
                "state": "draft"
            }

+ Response 200 (application/json)

+ Response 403 (application/json)  

<!-- include(planning-cancel.apib) -->

<!-- include(planning-post.apib) -->

<!-- include(planning-postpone.apib) -->
