## Planning Download Collection [/planning_download/events/{id}]

Downloads the exported event as a text file

+ Parameters

    - id (string) ... id

### Download A Planning Article [POST]

+ Request (application/json)

    + Body
        
            {

            }

    + Schema

            {
                "file": {"type": "file"}
            }


+ Response 201 (application/json)

+ Response 400 (application/json)

+ Response 412 (application/json)
